# Add nodes (cities)
cities = [
    "New York",
    "Los Angeles",
    "Chicago",
    "Houston",
    "Phoenix",
    "San Francisco",
    "Miami",
    "Denver",
    "Seattle",
    "Boston",
    "Atlanta",
    "Dallas",
    "San Diego",
    "Las Vegas",
    "Portland",
    "Philadelphia",
    "Minneapolis",
    "Detroit",
    "Austin",
    "Charlotte",
]

# Add weighted edges (connections with weights)
connections = [
    ("New York", "Los Angeles", 2800),
    ("New York", "Chicago", 800),
    ("Chicago", "Houston", 1080),
    ("Houston", "Phoenix", 1170),
    ("Los Angeles", "Phoenix", 370),
    ("Los Angeles", "San Francisco", 380),
    ("San Francisco", "Seattle", 810),
    ("Seattle", "Denver", 1300),
    ("Denver", "Chicago", 1000),
    ("Miami", "New York", 1300),
    ("Miami", "Houston", 1200),
    ("Boston", "New York", 215),
    ("Boston", "Chicago", 990),
    ("Denver", "Phoenix", 850),
    ("Seattle", "Boston", 3000),
    ("Atlanta", "New York", 870),
    ("Atlanta", "Miami", 660),
    ("Dallas", "Houston", 240),
    ("Dallas", "Denver", 790),
    ("San Diego", "Los Angeles", 120),
    ("San Diego", "Phoenix", 355),
    ("Las Vegas", "Los Angeles", 270),
    ("Las Vegas", "Phoenix", 300),
    ("Portland", "Seattle", 170),
    ("Portland", "San Francisco", 630),
    ("Philadelphia", "New York", 95),
    ("Philadelphia", "Boston", 310),
    ("Minneapolis", "Chicago", 410),
    ("Detroit", "Chicago", 280),
    ("Austin", "Houston", 160),
    ("Austin", "Dallas", 195),
    ("Charlotte", "Atlanta", 245),
    ("Charlotte", "New York", 630),
]
